data class RegisterHook(
    val nombre: String,
    val correo: String,
    val password: String,
    val confirmarPassword: String,
    val telefono: String,
    val genero: String,
    val edad: String,
    val descripcionPerfil: String,
    val ciudad: String,
    val roles: List<Pair<String, String>>,
    val rolSeleccionado: Pair<String, String>,
    val dropdownExpanded: Boolean,
    val cargando: Boolean,
    val onNombreChange: (String) -> Unit,
    val onCorreoChange: (String) -> Unit,
    val onPasswordChange: (String) -> Unit,
    val onConfirmarPasswordChange: (String) -> Unit,
    val onTelefonoChange: (String) -> Unit,
    val onGeneroChange: (String) -> Unit,
    val onEdadChange: (String) -> Unit,
    val onDescripcionChange: (String) -> Unit,
    val onCiudadChange: (String) -> Unit,
    val onRolSelected: (Pair<String, String>) -> Unit,
    val onDropdownToggle: () -> Unit,
    val onDropdownDismiss: () -> Unit,
    val onRegistrar: () -> Unit
)
