data class TiendaHook(
    val tienda: Store?,
    val name: String,
    val address: String,
    val phone: String,
    val description: String,
    val edit: Boolean,
    val guardando: Boolean,
    val cargando: Boolean,
    val errorMsg: String?,
    val unas: Boolean,
    val pestanas: Boolean,
    val cejas: Boolean,
    val barberia: Boolean,
    val cortesDama: Boolean,
    val onNameChange: (String) -> Unit,
    val onAddressChange: (String) -> Unit,
    val onPhoneChange: (String) -> Unit,
    val onDescriptionChange: (String) -> Unit,
    val onUnasChange: (Boolean) -> Unit,
    val onPestanasChange: (Boolean) -> Unit,
    val onCejasChange: (Boolean) -> Unit,
    val onBarberiaChange: (Boolean) -> Unit,
    val onCortesDamaChange: (Boolean) -> Unit,
    val onEditarGuardar: () -> Unit
)